version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
            git clone -b lineage-17.1 https://github.com/aslenofarid/kernel_asus_sdm660 kernel && cd kernel
            curl -s https://raw.githubusercontent.com/aslenofarid/Kernel_Builder_CI_LV_S/LV-S/build.sh | bash
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
